version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: .dockerfiles/BackendDev
    ports:
      - "5001:80"
    volumes:
      - "./:/code/app"
    restart: always
  db:
    image: mysql:8.0.3
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_rootpass
      MYSQL_DATABASE: db_1
    ports:
      - "3306:3306"
    restart: always
  mywebsql:
    image: quantumobject/docker-mywebsql
    ports:
      - "9001:80"
    restart: always
